rem Master script for DDL reverse engineering by TOra

@PACKAGE_OMQTEST_QORE_TEST.sql
@PACKAGE_BODY_OMQTEST_QORE_TEST.sql
@TYPE_OMQTEST_COL_TEST.sql
@TYPE_OMQTEST_COL_TEST_CLOB.sql
@TYPE_OMQTEST_COL_TEST_NUM.sql
@TYPE_OMQTEST_TEST_OBJECT.sql
